name: releaser
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'test'
env:
  NODE_OPTIONS: "--max-old-space-size=4096"  # 增加 Node.js 可用的最大内存，防止构建失败
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-client:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: gpp, platform: linux/amd64, os: ubuntu-latest },
          { name: gpp, platform: windows/amd64, os: windows-latest },
          { name: gpp, platform: darwin/universal, os: macos-latest }
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.22'